-- A reference of our own on every logged contractor invoice.
--
-- Their invoice number is theirs: it can be missing, it repeats between
-- contractors, and two of them will eventually both send an "INV-1". A record
-- that has to be quoted — on a landlord's statement, in an email asking what a
-- payment was for, between two people looking at the same screen — needs a
-- reference that belongs to us and means exactly one row.
--
-- Sequential rather than random (the complaints ref is random because it rides
-- in an email subject and must not be guessable; this one is read out and typed
-- back, so GC-CI-00007 beats GC-CI-4F9A2C), and generated by the column default
-- so there is no code path that can forget it and no collision to retry.
CREATE SEQUENCE IF NOT EXISTS contractor_invoice_ref_seq;

ALTER TABLE contractor_invoices ADD COLUMN IF NOT EXISTS ref TEXT;

-- Everything already logged gets one, oldest first, so the numbering reads in
-- the order the invoices arrived.
WITH ordered AS (
  SELECT id, row_number() OVER (ORDER BY created_at, id) AS n
    FROM contractor_invoices
   WHERE ref IS NULL
)
UPDATE contractor_invoices i
   SET ref = 'GC-CI-' || lpad(ordered.n::text, 5, '0')
  FROM ordered
 WHERE i.id = ordered.id;

-- Carry on from where the backfill finished.
SELECT setval(
  'contractor_invoice_ref_seq',
  GREATEST((SELECT count(*) FROM contractor_invoices), 1),
  (SELECT count(*) FROM contractor_invoices) > 0
);

ALTER TABLE contractor_invoices
  ALTER COLUMN ref SET DEFAULT 'GC-CI-' || lpad(nextval('contractor_invoice_ref_seq')::text, 5, '0');

CREATE UNIQUE INDEX IF NOT EXISTS idx_contractor_invoices_ref
  ON contractor_invoices (ref) WHERE ref IS NOT NULL;
