import { query, pool } from '../db/pool.js';
import { createComplaint } from '../services/complaintCreate.js';
const org = async (name, type, st, extra = '') => (await query(`INSERT INTO organisations (name, type, research_status${extra ? ', procedure_ref' : ''}) VALUES ($1,$2,$3${extra ? ',$4' : ''}) RETURNING *`, extra ? [name, type, st, extra] : [name, type, st])).rows[0];
const ovo = await org('OVO Energy', 'energy', 'none');
const bg = await org('British Gas', 'energy', 'researched', 'BG Complaints Code');
const lcc = await org('Liverpool City Council', 'council', 'document', 'Corporate Complaints Policy');
const cder = await org('CDER Group', 'debt_collector', 'none');
const mk = (o, subject, extra = {}) => createComplaint({ organisation_id: o?.id || null, org_name: o?.name || 'Octopus Energy', org_type: o?.type || 'energy', subject, raised_on: '2026-07-14', imported: true, account_numbers: ['28131442'], property: '165 Longton Lane, L35 8NU', ...extra }, { by: 'Import (read from the emails)', needsCheck: true });
const a = await mk(ovo, 'Disputed £90.33 closing balance and £20 late payment fee at vacant property');
const b = await mk(bg, 'Void period billing not disclosing full brought-forward balance', { account_numbers: ['A43198336'], property: '84 Waverley Crescent, Droylsden, M43 7WL', raised_on: '2026-08-20' });
await query(`INSERT INTO complaint_events (complaint_id, event_date, type, note, created_by) VALUES ($1, '2026-09-29', 'chased', 'Chased by email', 'Sam Kahan')`, [b.id]);
const c = await mk(lcc, 'Failure to update council tax account following notification of change of bill payer', { account_numbers: ['58669277'], property: 'Apartment 309, 2 Moorfields, Liverpool, L2 2BT', raised_on: '2026-07-09' });
await query(`INSERT INTO complaint_parties (complaint_id, organisation_id, org_name, org_type, raised_on, stage, state) VALUES ($1,$2,'CDER Group','debt_collector','2026-08-01','stage_1','open')`, [c.id, cder.id]);
const d = await mk(ovo, 'Old resolved OVO complaint', { account_numbers: ['99887766'] });
await query(`UPDATE complaints SET state = 'resolved', stage = 'resolved' WHERE id = $1`, [d.id]);
await mk(null, 'Octopus complaint with no saved organisation', { account_numbers: ['55443322'], raised_on: '2026-09-25' });
// A re-check that was running when the server stopped.
await query(`UPDATE complaints SET recheck_progress = '{"status":"running","step":"Reading its 14 emails","started_at":"2026-09-29T08:00:00Z","by":"Sam Kahan"}' WHERE id = $1`, [a.id]);
console.log('seeded');
await pool.end();
